Tracker:AddLayouts("layouts/item_grids.json")
Tracker:AddLayouts("layouts/options.json")
Tracker:AddLayouts("layouts/layouts.json")
Tracker:AddLayouts("layouts/capture_spawns.json")
Tracker:AddLayouts("layouts/capture_items.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/broadcast.json")
